spring:
  application:
    name: dubbo-consumer
server:
  port: 9091
api:
  service:
    version: 1.0.0
dubbo:
  application:
    id: dubbo-consumer-id-1
    name: dubbo-consumer-name-1
  registry:
    protocol: zookeeper
    address: 10.4.79.11:2181
    id: registry-1
management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'
